package message

import (
	"encoding/json"
	"fmt"
)

// MessageList is an ordered sequence of [Message] values representing a
// conversation history. It serialises to a JSON array where each element
// includes a "role" discriminator so the concrete message type can be
// reconstructed on decode.
type MessageList []Message

// MarshalText encodes the list using the same role-tagged JSON form used by MarshalJSON.
func (ml MessageList) MarshalText() ([]byte, error) {
	return ml.MarshalJSON()
}

// UnmarshalText decodes the role-tagged JSON form back into a typed MessageList.
func (ml *MessageList) UnmarshalText(data []byte) error {
	return ml.UnmarshalJSON(data)
}

// MarshalJSON encodes the list as a JSON array with an injected "role" field
// on every element so receivers can identify the message type without a wrapper object.
func (ml MessageList) MarshalJSON() ([]byte, error) {
	if ml == nil {
		return []byte("[]"), nil
	}

	messages := make([]json.RawMessage, len(ml))
	for i, msg := range ml {
		data, err := json.Marshal(msg)
		if err != nil {
			return nil, err
		}

		buf := make([]byte, 0, len(data)+len(msg.Role())+20) // extra space for role and JSON overhead
		buf = append(buf, '{')
		buf = append(buf, fmt.Sprintf(`"role":"%s",`, msg.Role())...)
		if len(data) > 2 { // if the marshaled message is not an empty JSON object
			buf = append(buf, data[1:len(data)-1]...) // strip the outer braces
		}
		buf = append(buf, '}')

		messages[i] = buf
	}

	return json.Marshal(messages)
}

// UnmarshalJSON decodes a JSON array of role-tagged objects back into a typed
// [MessageList], dispatching on the "role" field to select the correct concrete
// [Message] implementation.
func (ml *MessageList) UnmarshalJSON(data []byte) error {
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(data, &rawMessages); err != nil {
		return err
	}

	var messages []Message
	for _, raw := range rawMessages {
		var header struct {
			Role Role `json:"role"`
		}
		if err := json.Unmarshal(raw, &header); err != nil {
			return err
		}

		var msg Message
		switch header.Role {
		case RoleSystem:
			msg = &System{}
		case RoleAssistant:
			msg = &Assistant{}
		case RoleTool:
			msg = &Tool{}
		case RoleUser:
			msg = &User{}
		default:
			return fmt.Errorf("unknown role: %s", header.Role)
		}

		if err := json.Unmarshal(raw, msg); err != nil {
			return err
		}

		messages = append(messages, msg)
	}

	*ml = messages
	return nil
}

// Message is the sealed interface for all conversation turns.
// Concrete implementations — [System], [User], [Assistant], and [Tool] —
// are distinguished by their [Role] and carry a [Content] slice.
type Message interface {
	GetID() string
	SetID(string)
	Role() Role
	GetContent() Content
	GetMetadata() map[string]any
	SetMetadata(map[string]any)
	isMessage()
}

// Role identifies the participant that produced a message in the conversation.
type Role string

const (
	// RoleSystem marks instructions from the application developer.
	RoleSystem Role = "system"
	// RoleAssistant marks a response generated by the LLM.
	RoleAssistant Role = "assistant"
	// RoleTool marks the result returned after executing a tool call.
	RoleTool Role = "tool"
	// RoleUser marks a message from the human participant.
	RoleUser Role = "user"
)

// String returns the role as its underlying string value.
func (r Role) String() string {
	return string(r)
}

// Base carries the identity fields shared by all message types.
type Base struct {
	ID       string         `json:"id"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

// GetID returns the message identifier.
func (b *Base) GetID() string {
	return b.ID
}

// SetID sets the message identifier.
func (b *Base) SetID(id string) {
	b.ID = id
}

// GetMetadata returns the key/value metadata attached to this message.
func (b *Base) GetMetadata() map[string]any {
	return b.Metadata
}

// SetMetadata sets the key/value metadata attached to this message.
func (b *Base) SetMetadata(metadata map[string]any) {
	b.Metadata = metadata
}
