package message

import (
	"encoding/json"
	"fmt"
	"sync"
)

// MessageList is an ordered sequence of [Message] values representing a
// conversation history. It serialises to a JSON array where each element
// includes a "role" discriminator so the concrete message type can be
// reconstructed on decode.
type MessageList []Message

// MarshalText encodes the list using the same role-tagged JSON form used by MarshalJSON.
func (ml MessageList) MarshalText() ([]byte, error) {
	return ml.MarshalJSON()
}

// UnmarshalText decodes the role-tagged JSON form back into a typed MessageList.
func (ml *MessageList) UnmarshalText(data []byte) error {
	return ml.UnmarshalJSON(data)
}

// MarshalJSON encodes the list as a JSON array with an injected "role" field
// on every element so receivers can identify the message type without a wrapper object.
func (ml MessageList) MarshalJSON() ([]byte, error) {
	if ml == nil {
		return []byte("[]"), nil
	}

	messages := make([]json.RawMessage, len(ml))
	for i, msg := range ml {
		data, err := json.Marshal(msg)
		if err != nil {
			return nil, err
		}

		buf := make([]byte, 0, len(data)+len(msg.Role())+20) // extra space for role and JSON overhead
		buf = append(buf, '{')
		buf = append(buf, fmt.Sprintf(`"role":"%s",`, msg.Role())...)
		if len(data) > 2 { // if the marshaled message is not an empty JSON object
			buf = append(buf, data[1:len(data)-1]...) // strip the outer braces
		}
		buf = append(buf, '}')

		messages[i] = buf
	}

	return json.Marshal(messages)
}

// UnmarshalJSON decodes a JSON array of role-tagged objects back into a typed
// [MessageList], dispatching on the "role" field to select the correct concrete
// [Message] implementation.
func (ml *MessageList) UnmarshalJSON(data []byte) error {
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(data, &rawMessages); err != nil {
		return err
	}

	var messages []Message
	for _, raw := range rawMessages {
		var header struct {
			Role Role `json:"role"`
		}
		if err := json.Unmarshal(raw, &header); err != nil {
			return err
		}

		var msg Message
		switch header.Role {
		case RoleSystem:
			msg = &System{}
		case RoleAssistant:
			msg = &Assistant{}
		case RoleTool:
			msg = &Tool{}
		case RoleUser:
			msg = &User{}
		default:
			return fmt.Errorf("unknown role: %s", header.Role)
		}

		if err := json.Unmarshal(raw, msg); err != nil {
			return err
		}

		messages = append(messages, msg)
	}

	*ml = messages
	return nil
}

// Extension is the interface that all provider-specific message configurations
// must implement to be passed in a [Message].
type Extension interface {
	// ExtensionID returns a unique identifier for this extension type.
	ExtensionID() string
}

// ExtensionFactory is a function that creates a new instance of a concrete Extension.
type ExtensionFactory func() Extension

var (
	extensionRegistry   = make(map[string]ExtensionFactory)
	extensionRegistryMu sync.RWMutex
)

// RegisterExtension stores an extension factory in the global registry,
// allowing concrete types to be restored during JSON unmarshaling.
func RegisterExtension(factory ExtensionFactory) {
	extensionRegistryMu.Lock()
	defer extensionRegistryMu.Unlock()
	ext := factory()
	extensionRegistry[ext.ExtensionID()] = factory
}

// ExtensionMap is a collection of provider-specific configurations keyed by their ID.
// It implements custom JSON unmarshaling to restore concrete types from the registry.
type ExtensionMap map[string]Extension

// UnmarshalJSON decodes a JSON object into an ExtensionMap, using the global
// registry to instantiate the correct concrete types for each key.
func (m *ExtensionMap) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	*m = make(ExtensionMap)
	extensionRegistryMu.RLock()
	defer extensionRegistryMu.RUnlock()

	for id, rawVal := range raw {
		if factory, ok := extensionRegistry[id]; ok {
			ext := factory()
			if err := json.Unmarshal(rawVal, ext); err != nil {
				return fmt.Errorf("failed to unmarshal message extension %q: %w", id, err)
			}
			(*m)[id] = ext
		} else {
			// If not in registry, we skip it to avoid data corruption.
			continue
		}
	}
	return nil
}

// Message is the sealed interface for all conversation turns.
// Concrete implementations — [System], [User], [Assistant], and [Tool] —
// are distinguished by their [Role] and carry a [Content] slice.
type Message interface {
	GetID() string
	SetID(string)
	Role() Role
	GetContent() Content
	GetMetadata() map[string]any
	SetMetadata(map[string]any)
	GetExtensions() ExtensionMap
	SetExtensions(ExtensionMap)
	AddExtension(Extension)
	isMessage()
}

// Role identifies the participant that produced a message in the conversation.
type Role string

const (
	// RoleSystem marks instructions from the application developer.
	RoleSystem Role = "system"
	// RoleAssistant marks a response generated by the LLM.
	RoleAssistant Role = "assistant"
	// RoleTool marks the result returned after executing a tool call.
	RoleTool Role = "tool"
	// RoleUser marks a message from the human participant.
	RoleUser Role = "user"
)

// String returns the role as its underlying string value.
func (r Role) String() string {
	return string(r)
}

// Base carries the identity fields shared by all message types.
type Base struct {
	ID         string         `json:"id"`
	Metadata   map[string]any `json:"metadata,omitempty"`
	Extensions ExtensionMap   `json:"extensions,omitempty"`
}

// GetID returns the message identifier.
func (b *Base) GetID() string {
	return b.ID
}

// SetID sets the message identifier.
func (b *Base) SetID(id string) {
	b.ID = id
}

// GetMetadata returns the key/value metadata attached to this message.
func (b *Base) GetMetadata() map[string]any {
	return b.Metadata
}

// SetMetadata sets the key/value metadata attached to this message.
func (b *Base) SetMetadata(metadata map[string]any) {
	b.Metadata = metadata
}

// GetExtensions returns the provider-specific configurations attached to this message.
func (b *Base) GetExtensions() ExtensionMap {
	return b.Extensions
}

// SetExtensions sets the provider-specific configurations attached to this message.
func (b *Base) SetExtensions(extensions ExtensionMap) {
	b.Extensions = extensions
}

// AddExtension attaches a single provider-specific configuration to this message.
func (b *Base) AddExtension(ext Extension) {
	if b.Extensions == nil {
		b.Extensions = make(ExtensionMap)
	}
	b.Extensions[ext.ExtensionID()] = ext
}
