// Code generated by loomgen; DO NOT EDIT.
// This file was generated by running the command:
//   loomgen llm-profiles -provider=openai -out=profiles.gen.go -pkg=loomopenai

package loomopenai

import "github.com/masterkeysrd/loom/llm"

var staticProfiles = map[string]llm.ModelProfile{
	"chatgpt-image-latest": {
		ID:     "chatgpt-image-latest",
		Name:   "chatgpt-image-latest",
		Family: "gpt-image",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 0,
			Output:  0,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-3.5-turbo": {
		ID:     "gpt-3.5-turbo",
		Name:   "GPT-3.5-turbo",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 16385,
			Output:  4096,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.5,
			Output:     1.5,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-4": {
		ID:     "gpt-4",
		Name:   "GPT-4",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 8192,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      30,
			Output:     60,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-4-turbo": {
		ID:     "gpt-4-turbo",
		Name:   "GPT-4 Turbo",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  4096,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      10,
			Output:     30,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-4.1": {
		ID:     "gpt-4.1",
		Name:   "GPT-4.1",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1047576,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2,
			Output:     8,
			CacheRead:  0.5,
			CacheWrite: 0,
		},
	},
	"gpt-4.1-mini": {
		ID:     "gpt-4.1-mini",
		Name:   "GPT-4.1 mini",
		Family: "gpt-mini",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1047576,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.4,
			Output:     1.6,
			CacheRead:  0.1,
			CacheWrite: 0,
		},
	},
	"gpt-4.1-nano": {
		ID:     "gpt-4.1-nano",
		Name:   "GPT-4.1 nano",
		Family: "gpt-nano",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1047576,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.1,
			Output:     0.4,
			CacheRead:  0.025,
			CacheWrite: 0,
		},
	},
	"gpt-4o": {
		ID:     "gpt-4o",
		Name:   "GPT-4o",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2.5,
			Output:     10,
			CacheRead:  1.25,
			CacheWrite: 0,
		},
	},
	"gpt-4o-2024-05-13": {
		ID:     "gpt-4o-2024-05-13",
		Name:   "GPT-4o (2024-05-13)",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  4096,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      5,
			Output:     15,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-4o-2024-08-06": {
		ID:     "gpt-4o-2024-08-06",
		Name:   "GPT-4o (2024-08-06)",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2.5,
			Output:     10,
			CacheRead:  1.25,
			CacheWrite: 0,
		},
	},
	"gpt-4o-2024-11-20": {
		ID:     "gpt-4o-2024-11-20",
		Name:   "GPT-4o (2024-11-20)",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2.5,
			Output:     10,
			CacheRead:  1.25,
			CacheWrite: 0,
		},
	},
	"gpt-4o-mini": {
		ID:     "gpt-4o-mini",
		Name:   "GPT-4o mini",
		Family: "gpt-mini",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.15,
			Output:     0.6,
			CacheRead:  0.075,
			CacheWrite: 0,
		},
	},
	"gpt-5": {
		ID:     "gpt-5",
		Name:   "GPT-5",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
		},
	},
	"gpt-5-chat-latest": {
		ID:     "gpt-5-chat-latest",
		Name:   "GPT-5 Chat (latest)",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
		},
	},
	"gpt-5-codex": {
		ID:     "gpt-5-codex",
		Name:   "GPT-5-Codex",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
		},
	},
	"gpt-5-mini": {
		ID:     "gpt-5-mini",
		Name:   "GPT-5 Mini",
		Family: "gpt-mini",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.25,
			Output:     2,
			CacheRead:  0.025,
			CacheWrite: 0,
		},
	},
	"gpt-5-nano": {
		ID:     "gpt-5-nano",
		Name:   "GPT-5 Nano",
		Family: "gpt-nano",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.05,
			Output:     0.4,
			CacheRead:  0.005,
			CacheWrite: 0,
		},
	},
	"gpt-5-pro": {
		ID:     "gpt-5-pro",
		Name:   "GPT-5 Pro",
		Family: "gpt-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  272000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     120,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-5.1": {
		ID:     "gpt-5.1",
		Name:   "GPT-5.1",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
		},
	},
	"gpt-5.1-chat-latest": {
		ID:     "gpt-5.1-chat-latest",
		Name:   "GPT-5.1 Chat",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
		},
	},
	"gpt-5.1-codex": {
		ID:     "gpt-5.1-codex",
		Name:   "GPT-5.1 Codex",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
		},
	},
	"gpt-5.1-codex-max": {
		ID:     "gpt-5.1-codex-max",
		Name:   "GPT-5.1 Codex Max",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
		},
	},
	"gpt-5.1-codex-mini": {
		ID:     "gpt-5.1-codex-mini",
		Name:   "GPT-5.1 Codex mini",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.25,
			Output:     2,
			CacheRead:  0.025,
			CacheWrite: 0,
		},
	},
	"gpt-5.2": {
		ID:     "gpt-5.2",
		Name:   "GPT-5.2",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.75,
			Output:     14,
			CacheRead:  0.175,
			CacheWrite: 0,
		},
	},
	"gpt-5.2-chat-latest": {
		ID:     "gpt-5.2-chat-latest",
		Name:   "GPT-5.2 Chat",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.75,
			Output:     14,
			CacheRead:  0.175,
			CacheWrite: 0,
		},
	},
	"gpt-5.2-codex": {
		ID:     "gpt-5.2-codex",
		Name:   "GPT-5.2 Codex",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.75,
			Output:     14,
			CacheRead:  0.175,
			CacheWrite: 0,
		},
	},
	"gpt-5.2-pro": {
		ID:     "gpt-5.2-pro",
		Name:   "GPT-5.2 Pro",
		Family: "gpt-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      21,
			Output:     168,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-5.3-chat-latest": {
		ID:     "gpt-5.3-chat-latest",
		Name:   "GPT-5.3 Chat (latest)",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.75,
			Output:     14,
			CacheRead:  0.175,
			CacheWrite: 0,
		},
	},
	"gpt-5.3-codex": {
		ID:     "gpt-5.3-codex",
		Name:   "GPT-5.3 Codex",
		Family: "gpt-codex",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.75,
			Output:     14,
			CacheRead:  0.175,
			CacheWrite: 0,
		},
	},
	"gpt-5.3-codex-spark": {
		ID:     "gpt-5.3-codex-spark",
		Name:   "GPT-5.3 Codex Spark",
		Family: "gpt-codex-spark",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  32000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.75,
			Output:     14,
			CacheRead:  0.175,
			CacheWrite: 0,
		},
	},
	"gpt-5.4": {
		ID:     "gpt-5.4",
		Name:   "GPT-5.4",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 1050000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2.5,
			Output:     15,
			CacheRead:  0.25,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      5,
					Output:     22.5,
					CacheRead:  0.5,
					CacheWrite: 0,
					TierLimit:  272000,
				},
			},
		},
	},
	"gpt-5.4-mini": {
		ID:     "gpt-5.4-mini",
		Name:   "GPT-5.4 mini",
		Family: "gpt-mini",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.75,
			Output:     4.5,
			CacheRead:  0.075,
			CacheWrite: 0,
		},
	},
	"gpt-5.4-nano": {
		ID:     "gpt-5.4-nano",
		Name:   "GPT-5.4 nano",
		Family: "gpt-nano",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 400000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.2,
			Output:     1.25,
			CacheRead:  0.02,
			CacheWrite: 0,
		},
	},
	"gpt-5.4-pro": {
		ID:     "gpt-5.4-pro",
		Name:   "GPT-5.4 Pro",
		Family: "gpt-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 1050000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      30,
			Output:     180,
			CacheRead:  0,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      60,
					Output:     270,
					CacheRead:  0,
					CacheWrite: 0,
					TierLimit:  272000,
				},
			},
		},
	},
	"gpt-5.5": {
		ID:     "gpt-5.5",
		Name:   "GPT-5.5",
		Family: "gpt",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 1050000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      5,
			Output:     30,
			CacheRead:  0.5,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      10,
					Output:     45,
					CacheRead:  1,
					CacheWrite: 0,
					TierLimit:  272000,
				},
			},
		},
	},
	"gpt-5.5-pro": {
		ID:     "gpt-5.5-pro",
		Name:   "GPT-5.5 Pro",
		Family: "gpt-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 1050000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      30,
			Output:     180,
			CacheRead:  0,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      60,
					Output:     270,
					CacheRead:  0,
					CacheWrite: 0,
					TierLimit:  272000,
				},
			},
		},
	},
	"gpt-image-1": {
		ID:     "gpt-image-1",
		Name:   "gpt-image-1",
		Family: "gpt-image",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 0,
			Output:  0,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-image-1-mini": {
		ID:     "gpt-image-1-mini",
		Name:   "gpt-image-1-mini",
		Family: "gpt-image",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 0,
			Output:  0,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gpt-image-1.5": {
		ID:     "gpt-image-1.5",
		Name:   "gpt-image-1.5",
		Family: "gpt-image",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 0,
			Output:  0,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"o1": {
		ID:     "o1",
		Name:   "o1",
		Family: "o",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     60,
			CacheRead:  7.5,
			CacheWrite: 0,
		},
	},
	"o1-mini": {
		ID:     "o1-mini",
		Name:   "o1-mini",
		Family: "o-mini",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.1,
			Output:     4.4,
			CacheRead:  0.55,
			CacheWrite: 0,
		},
	},
	"o1-preview": {
		ID:     "o1-preview",
		Name:   "o1-preview",
		Family: "o",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     60,
			CacheRead:  7.5,
			CacheWrite: 0,
		},
	},
	"o1-pro": {
		ID:     "o1-pro",
		Name:   "o1-pro",
		Family: "o-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      150,
			Output:     600,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"o3": {
		ID:     "o3",
		Name:   "o3",
		Family: "o",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2,
			Output:     8,
			CacheRead:  0.5,
			CacheWrite: 0,
		},
	},
	"o3-deep-research": {
		ID:     "o3-deep-research",
		Name:   "o3-deep-research",
		Family: "o",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      10,
			Output:     40,
			CacheRead:  2.5,
			CacheWrite: 0,
		},
	},
	"o3-mini": {
		ID:     "o3-mini",
		Name:   "o3-mini",
		Family: "o-mini",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.1,
			Output:     4.4,
			CacheRead:  0.55,
			CacheWrite: 0,
		},
	},
	"o3-pro": {
		ID:     "o3-pro",
		Name:   "o3-pro",
		Family: "o-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      20,
			Output:     80,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"o4-mini": {
		ID:     "o4-mini",
		Name:   "o4-mini",
		Family: "o-mini",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.1,
			Output:     4.4,
			CacheRead:  0.275,
			CacheWrite: 0,
		},
	},
	"o4-mini-deep-research": {
		ID:     "o4-mini-deep-research",
		Name:   "o4-mini-deep-research",
		Family: "o-mini",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  100000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2,
			Output:     8,
			CacheRead:  0.5,
			CacheWrite: 0,
		},
	},
	"text-embedding-3-large": {
		ID:     "text-embedding-3-large",
		Name:   "text-embedding-3-large",
		Family: "text-embedding",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 8191,
			Output:  3072,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.13,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"text-embedding-3-small": {
		ID:     "text-embedding-3-small",
		Name:   "text-embedding-3-small",
		Family: "text-embedding",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 8191,
			Output:  1536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.02,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"text-embedding-ada-002": {
		ID:     "text-embedding-ada-002",
		Name:   "text-embedding-ada-002",
		Family: "text-embedding",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 8192,
			Output:  1536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.1,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
}
