// Code generated by loomgen; DO NOT EDIT.
// This file was generated by running the command:
//   loomgen llm-profiles -provider=anthropic -out=profiles.gen.go -pkg=loomanthropic

package loomanthropic

import "github.com/masterkeysrd/loom/llm"

var staticProfiles = map[string]llm.ModelProfile{
	"claude-3-5-haiku-20241022": {
		ID:     "claude-3-5-haiku-20241022",
		Name:   "Claude Haiku 3.5",
		Family: "claude-haiku",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.8,
			Output:     4,
			CacheRead:  0.08,
			CacheWrite: 1,
		},
	},
	"claude-3-5-haiku-latest": {
		ID:     "claude-3-5-haiku-latest",
		Name:   "Claude Haiku 3.5 (latest)",
		Family: "claude-haiku",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.8,
			Output:     4,
			CacheRead:  0.08,
			CacheWrite: 1,
		},
	},
	"claude-3-5-sonnet-20240620": {
		ID:     "claude-3-5-sonnet-20240620",
		Name:   "Claude Sonnet 3.5",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
	"claude-3-5-sonnet-20241022": {
		ID:     "claude-3-5-sonnet-20241022",
		Name:   "Claude Sonnet 3.5 v2",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
	"claude-3-7-sonnet-20250219": {
		ID:     "claude-3-7-sonnet-20250219",
		Name:   "Claude Sonnet 3.7",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
	"claude-3-haiku-20240307": {
		ID:     "claude-3-haiku-20240307",
		Name:   "Claude Haiku 3",
		Family: "claude-haiku",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  4096,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.25,
			Output:     1.25,
			CacheRead:  0.03,
			CacheWrite: 0.3,
		},
	},
	"claude-3-opus-20240229": {
		ID:     "claude-3-opus-20240229",
		Name:   "Claude Opus 3",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  4096,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     75,
			CacheRead:  1.5,
			CacheWrite: 18.75,
		},
	},
	"claude-3-sonnet-20240229": {
		ID:     "claude-3-sonnet-20240229",
		Name:   "Claude Sonnet 3",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  4096,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 0.3,
		},
	},
	"claude-haiku-4-5": {
		ID:     "claude-haiku-4-5",
		Name:   "Claude Haiku 4.5 (latest)",
		Family: "claude-haiku",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1,
			Output:     5,
			CacheRead:  0.1,
			CacheWrite: 1.25,
		},
	},
	"claude-haiku-4-5-20251001": {
		ID:     "claude-haiku-4-5-20251001",
		Name:   "Claude Haiku 4.5",
		Family: "claude-haiku",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1,
			Output:     5,
			CacheRead:  0.1,
			CacheWrite: 1.25,
		},
	},
	"claude-opus-4-0": {
		ID:     "claude-opus-4-0",
		Name:   "Claude Opus 4 (latest)",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  32000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     75,
			CacheRead:  1.5,
			CacheWrite: 18.75,
		},
	},
	"claude-opus-4-1": {
		ID:     "claude-opus-4-1",
		Name:   "Claude Opus 4.1 (latest)",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  32000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     75,
			CacheRead:  1.5,
			CacheWrite: 18.75,
		},
	},
	"claude-opus-4-1-20250805": {
		ID:     "claude-opus-4-1-20250805",
		Name:   "Claude Opus 4.1",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  32000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     75,
			CacheRead:  1.5,
			CacheWrite: 18.75,
		},
	},
	"claude-opus-4-20250514": {
		ID:     "claude-opus-4-20250514",
		Name:   "Claude Opus 4",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  32000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      15,
			Output:     75,
			CacheRead:  1.5,
			CacheWrite: 18.75,
		},
	},
	"claude-opus-4-5": {
		ID:     "claude-opus-4-5",
		Name:   "Claude Opus 4.5 (latest)",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      5,
			Output:     25,
			CacheRead:  0.5,
			CacheWrite: 6.25,
		},
	},
	"claude-opus-4-5-20251101": {
		ID:     "claude-opus-4-5-20251101",
		Name:   "Claude Opus 4.5",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      5,
			Output:     25,
			CacheRead:  0.5,
			CacheWrite: 6.25,
		},
	},
	"claude-opus-4-6": {
		ID:     "claude-opus-4-6",
		Name:   "Claude Opus 4.6",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      5,
			Output:     25,
			CacheRead:  0.5,
			CacheWrite: 6.25,
		},
	},
	"claude-opus-4-7": {
		ID:     "claude-opus-4-7",
		Name:   "Claude Opus 4.7",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      5,
			Output:     25,
			CacheRead:  0.5,
			CacheWrite: 6.25,
		},
	},
	"claude-opus-4-8": {
		ID:     "claude-opus-4-8",
		Name:   "Claude Opus 4.8",
		Family: "claude-opus",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  128000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      5,
			Output:     25,
			CacheRead:  0.5,
			CacheWrite: 6.25,
		},
	},
	"claude-sonnet-4-0": {
		ID:     "claude-sonnet-4-0",
		Name:   "Claude Sonnet 4 (latest)",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
	"claude-sonnet-4-20250514": {
		ID:     "claude-sonnet-4-20250514",
		Name:   "Claude Sonnet 4",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
	"claude-sonnet-4-5": {
		ID:     "claude-sonnet-4-5",
		Name:   "Claude Sonnet 4.5 (latest)",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
	"claude-sonnet-4-5-20250929": {
		ID:     "claude-sonnet-4-5-20250929",
		Name:   "Claude Sonnet 4.5",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 200000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
	"claude-sonnet-4-6": {
		ID:     "claude-sonnet-4-6",
		Name:   "Claude Sonnet 4.6",
		Family: "claude-sonnet",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      3,
			Output:     15,
			CacheRead:  0.3,
			CacheWrite: 3.75,
		},
	},
}
