package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"sort"
	"strings"
	"text/template"
)

func main() {
	args := os.Args
	if len(args) < 2 {
		fmt.Println("Usage: loomgen <command> [flags]")
		os.Exit(1)
	}

	switch args[1] {
	case "llm-profiles":
		if err := generateLLMProfiles(); err != nil {
			fmt.Printf("Error generating LLM profiles: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Printf("Unknown command: %s\n", args[1])
		os.Exit(1)
	}
}

func generateLLMProfiles() error {
	const modelsDevURL = "https://models.dev/api.json"

	flagSet := flag.NewFlagSet("llm-profiles", flag.ExitOnError)
	var (
		pkg      string
		provider string
		output   string
	)

	flagSet.StringVar(&provider, "provider", "", "LLM provider (e.g., 'ollama', 'anthropic')")
	flagSet.StringVar(&output, "out", "profiles.gen.go", "Output file name")
	flagSet.StringVar(&pkg, "pkg", os.Getenv("GOPACKAGE"), "Target package name")

	if err := flagSet.Parse(os.Args[2:]); err != nil {
		return err
	}

	if provider == "" || pkg == "" {
		flagSet.Usage()
		return fmt.Errorf("missing required flags: -provider and -pkg")
	}

	fmt.Printf("Fetching profiles for %q from models.dev...\n", provider)
	resp, err := http.Get(modelsDevURL)
	if err != nil {
		return fmt.Errorf("fetch failed: %w", err)
	}
	defer resp.Body.Close()

	var all map[string]providerEntry
	if err := json.NewDecoder(resp.Body).Decode(&all); err != nil {
		return fmt.Errorf("decode failed: %w", err)
	}

	data, ok := all[provider]
	if !ok {
		return fmt.Errorf("provider %q not found", provider)
	}

	// Prepare data for template
	type templateData struct {
		Package string
		Models  []modelEntry
	}

	tData := templateData{
		Package: pkg,
		Models:  make([]modelEntry, 0, len(data.Models)),
	}

	for _, m := range data.Models {
		tData.Models = append(tData.Models, m)
	}

	// Sort models by ID for deterministic output
	sort.Slice(tData.Models, func(i, j int) bool {
		return tData.Models[i].ID < tData.Models[j].ID
	})

	buf := &bytes.Buffer{}
	if err := profileTemplate.Execute(buf, tData); err != nil {
		return fmt.Errorf("template execution failed: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("code formatting failed: %w", err)
	}

	f, err := os.Create(output)
	if err != nil {
		return err
	}
	defer f.Close()

	if _, err := f.Write(formatted); err != nil {
		return err
	}

	return nil
}

type providerEntry struct {
	Models map[string]modelEntry `json:"models"`
}

type modelEntry struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Family           string `json:"family"`
	Attachment       bool   `json:"attachment"`
	Reasoning        bool   `json:"reasoning"`
	ReasoningOptions []struct {
		Type   string   `json:"type"`
		Values []string `json:"values"`
	} `json:"reasoning_options"`
	ToolCall    bool `json:"tool_call"`
	Temperature bool `json:"temperature"`
	Modalities  struct {
		Input  []string `json:"input"`
		Output []string `json:"output"`
	} `json:"modalities"`
	Limit struct {
		Context int `json:"context"`
		Output  int `json:"output"`
	} `json:"limit"`
	OpenWeights bool `json:"open_weights,omitempty"`
	Cost        struct {
		Input      float64 `json:"input"`
		Output     float64 `json:"output"`
		CacheRead  float64 `json:"cache_read"`
		CacheWrite float64 `json:"cache_write"`
		Tiers      []struct {
			Input      float64 `json:"input"`
			Output     float64 `json:"output"`
			CacheRead  float64 `json:"cache_read"`
			CacheWrite float64 `json:"cache_write"`
			Tier       struct {
				Type string `json:"type"`
				Size int    `json:"size"`
			} `json:"tier"`
		} `json:"tiers"`
	} `json:"cost"`
}

var profileTemplate = template.Must(template.New("").
	Funcs(template.FuncMap{
		"format_modality": formatModality,
		"print_command":   printCommand,
	}).
	Parse(`// Code generated by loomgen; DO NOT EDIT.
// This file was generated by running the command:
//   {{ print_command }}

package {{.Package}}

import "github.com/masterkeysrd/loom/llm"

var staticProfiles = map[string]llm.ModelProfile{
{{- range .Models }}
	{{ printf "%q" .ID }}: {
		ID:     {{ printf "%q" .ID }},
		Name:   {{ printf "%q" .Name }},
		Family: {{ printf "%q" .Family }},
		Capabilities: llm.Capabilities{
			Attachment:  {{ .Attachment }},
			Reasoning:   {{ .Reasoning }},
			ToolCall:    {{ .ToolCall }},
			Temperature: {{ .Temperature }},
			{{- if .ReasoningOptions }}
			ReasoningOptions: []llm.ReasoningOption{
				{{- range .ReasoningOptions }}
				{
					Type: {{ printf "%q" .Type }},
					{{- if .Values }}
					Values: []string{
						{{- range .Values }}
						{{ printf "%q" . }},
						{{- end }}
					},
					{{- end }}
				},
				{{- end }}
			},
			{{- end }}
		},
		Limits: llm.ProfileLimits{
			Context: {{ .Limit.Context }},
			Output:  {{ .Limit.Output }},
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				{{- range .Modalities.Input }}
				{{ format_modality . }},
				{{- end }}
			},
			Outputs: []llm.Modality{
				{{- range .Modalities.Output }}
				{{ format_modality . }},
				{{- end }}
			},
		},
		OpenWeights: {{ .OpenWeights }},
		Pricing: llm.Pricing{
			Input:      {{ .Cost.Input }},
			Output:     {{ .Cost.Output }},
			CacheRead:  {{ .Cost.CacheRead }},
			CacheWrite: {{ .Cost.CacheWrite }},
			{{- if .Cost.Tiers }}
			TieredLimits: []llm.TierPricing{
				{{- range .Cost.Tiers }}
				{
					Input:      {{ .Input }},
					Output:     {{ .Output }},
					CacheRead:  {{ .CacheRead }},
					CacheWrite: {{ .CacheWrite }},
					TierLimit:  {{ .Tier.Size }},
				},
				{{- end }}
			},
			{{- end }}
		},
	},
{{- end }}
}
`))

func formatModality(m string) string {
	switch m {
	case "text":
		return "llm.ModalityText"
	case "image":
		return "llm.ModalityImage"
	case "audio":
		return "llm.ModalityAudio"
	case "video":
		return "llm.ModalityVideo"
	case "pdf":
		return "llm.ModalityPDF"
	default:
		return fmt.Sprintf("// Unknown modality: %q", m)
	}
}

func printCommand() string {
	var cmd strings.Builder
	for _, arg := range os.Args {
		if strings.Contains(arg, " ") {
			fmt.Fprintf(&cmd, "%q ", arg)
		} else {
			cmd.WriteString(arg + " ")
		}
	}
	return strings.TrimSpace(cmd.String())
}
