// Code generated by loomgen; DO NOT EDIT.
// This file was generated by running the command:
//   loomgen llm-profiles -provider=google -out=profiles.gen.go -pkg=loomgenai

package loomgenai

import "github.com/masterkeysrd/loom/llm"

var staticProfiles = map[string]llm.ModelProfile{
	"gemini-2.0-flash": {
		ID:          "gemini-2.0-flash",
		Name:        "Gemini 2.0 Flash",
		Family:      "gemini-flash",
		Knowledge:   "2024-06",
		ReleaseDate: "2024-12-11",
		LastUpdated: "2024-12-11",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.1,
			Output:     0.4,
			CacheRead:  0.025,
			CacheWrite: 0,
		},
	},
	"gemini-2.0-flash-lite": {
		ID:          "gemini-2.0-flash-lite",
		Name:        "Gemini 2.0 Flash-Lite",
		Family:      "gemini-flash-lite",
		Knowledge:   "2024-06",
		ReleaseDate: "2024-12-11",
		LastUpdated: "2024-12-11",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.075,
			Output:     0.3,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemini-2.5-flash": {
		ID:          "gemini-2.5-flash",
		Name:        "Gemini 2.5 Flash",
		Family:      "gemini-flash",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-06-17",
		LastUpdated: "2025-06-17",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "toggle",
				},
				{
					Type: "budget_tokens",
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.3,
			Output:     2.5,
			CacheRead:  0.03,
			CacheWrite: 0,
		},
	},
	"gemini-2.5-flash-image": {
		ID:          "gemini-2.5-flash-image",
		Name:        "Nano Banana",
		Family:      "gemini-flash",
		Knowledge:   "2025-06",
		ReleaseDate: "2025-08-26",
		LastUpdated: "2025-08-26",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 32768,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.3,
			Output:     30,
			CacheRead:  0.075,
			CacheWrite: 0,
		},
	},
	"gemini-2.5-flash-lite": {
		ID:          "gemini-2.5-flash-lite",
		Name:        "Gemini 2.5 Flash-Lite",
		Family:      "gemini-flash-lite",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-06-17",
		LastUpdated: "2025-06-17",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "toggle",
				},
				{
					Type: "budget_tokens",
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.1,
			Output:     0.4,
			CacheRead:  0.01,
			CacheWrite: 0,
		},
	},
	"gemini-2.5-flash-preview-tts": {
		ID:          "gemini-2.5-flash-preview-tts",
		Name:        "Gemini 2.5 Flash Preview TTS",
		Family:      "gemini-flash",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-05-01",
		LastUpdated: "2025-05-01",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 8192,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityAudio,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.5,
			Output:     10,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemini-2.5-pro": {
		ID:          "gemini-2.5-pro",
		Name:        "Gemini 2.5 Pro",
		Family:      "gemini-pro",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-06-17",
		LastUpdated: "2025-06-17",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "budget_tokens",
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.25,
			Output:     10,
			CacheRead:  0.125,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      2.5,
					Output:     15,
					CacheRead:  0.25,
					CacheWrite: 0,
					TierLimit:  200000,
				},
			},
		},
	},
	"gemini-2.5-pro-preview-tts": {
		ID:          "gemini-2.5-pro-preview-tts",
		Name:        "Gemini 2.5 Pro Preview TTS",
		Family:      "gemini-flash",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-05-01",
		LastUpdated: "2025-05-01",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 8192,
			Output:  16384,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityAudio,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1,
			Output:     20,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemini-3-flash-preview": {
		ID:          "gemini-3-flash-preview",
		Name:        "Gemini 3 Flash Preview",
		Family:      "gemini-flash",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-12-17",
		LastUpdated: "2025-12-17",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"minimal",
						"low",
						"medium",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.5,
			Output:     3,
			CacheRead:  0.05,
			CacheWrite: 0,
		},
	},
	"gemini-3-pro-image-preview": {
		ID:          "gemini-3-pro-image-preview",
		Name:        "Nano Banana Pro",
		Family:      "gemini-pro",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-11-20",
		LastUpdated: "2025-11-20",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 131072,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2,
			Output:     120,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemini-3-pro-preview": {
		ID:          "gemini-3-pro-preview",
		Name:        "Gemini 3 Pro Preview",
		Family:      "gemini-pro",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-11-18",
		LastUpdated: "2025-11-18",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"low",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2,
			Output:     12,
			CacheRead:  0.2,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      4,
					Output:     18,
					CacheRead:  0.4,
					CacheWrite: 0,
					TierLimit:  200000,
				},
			},
		},
	},
	"gemini-3.1-flash-image-preview": {
		ID:          "gemini-3.1-flash-image-preview",
		Name:        "Nano Banana 2",
		Family:      "gemini-flash",
		Knowledge:   "2025-01",
		ReleaseDate: "2026-02-26",
		LastUpdated: "2026-02-26",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"minimal",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 65536,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.5,
			Output:     60,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemini-3.1-flash-lite": {
		ID:          "gemini-3.1-flash-lite",
		Name:        "Gemini 3.1 Flash Lite",
		Family:      "gemini-flash-lite",
		Knowledge:   "2025-01",
		ReleaseDate: "2026-05-07",
		LastUpdated: "2026-05-07",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"minimal",
						"low",
						"medium",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.25,
			Output:     1.5,
			CacheRead:  0.025,
			CacheWrite: 0,
		},
	},
	"gemini-3.1-flash-lite-preview": {
		ID:          "gemini-3.1-flash-lite-preview",
		Name:        "Gemini 3.1 Flash Lite Preview",
		Family:      "gemini-flash-lite",
		Knowledge:   "2025-01",
		ReleaseDate: "2026-03-03",
		LastUpdated: "2026-03-03",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"minimal",
						"low",
						"medium",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.25,
			Output:     1.5,
			CacheRead:  0.025,
			CacheWrite: 0,
		},
	},
	"gemini-3.1-pro-preview": {
		ID:          "gemini-3.1-pro-preview",
		Name:        "Gemini 3.1 Pro Preview",
		Family:      "gemini-pro",
		Knowledge:   "2025-01",
		ReleaseDate: "2026-02-19",
		LastUpdated: "2026-02-19",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"low",
						"medium",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2,
			Output:     12,
			CacheRead:  0.2,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      4,
					Output:     18,
					CacheRead:  0.4,
					CacheWrite: 0,
					TierLimit:  200000,
				},
			},
		},
	},
	"gemini-3.1-pro-preview-customtools": {
		ID:          "gemini-3.1-pro-preview-customtools",
		Name:        "Gemini 3.1 Pro Preview Custom Tools",
		Family:      "gemini-pro",
		Knowledge:   "2025-01",
		ReleaseDate: "2026-02-19",
		LastUpdated: "2026-02-19",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"low",
						"medium",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      2,
			Output:     12,
			CacheRead:  0.2,
			CacheWrite: 0,
			TieredLimits: []llm.TierPricing{
				{
					Input:      4,
					Output:     18,
					CacheRead:  0.4,
					CacheWrite: 0,
					TierLimit:  200000,
				},
			},
		},
	},
	"gemini-3.5-flash": {
		ID:          "gemini-3.5-flash",
		Name:        "Gemini 3.5 Flash",
		Family:      "gemini-flash",
		Knowledge:   "2025-01",
		ReleaseDate: "2026-05-19",
		LastUpdated: "2026-05-19",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "effort",
					Values: []string{
						"minimal",
						"low",
						"medium",
						"high",
					},
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.5,
			Output:     9,
			CacheRead:  0.15,
			CacheWrite: 0,
		},
	},
	"gemini-embedding-001": {
		ID:          "gemini-embedding-001",
		Name:        "Gemini Embedding 001",
		Family:      "gemini",
		Knowledge:   "2025-05",
		ReleaseDate: "2025-05-20",
		LastUpdated: "2025-05-20",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 2048,
			Output:  1,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.15,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemini-flash-latest": {
		ID:          "gemini-flash-latest",
		Name:        "Gemini Flash Latest",
		Family:      "gemini-flash",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-09-25",
		LastUpdated: "2025-09-25",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "toggle",
				},
				{
					Type: "budget_tokens",
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.3,
			Output:     2.5,
			CacheRead:  0.075,
			CacheWrite: 0,
		},
	},
	"gemini-flash-lite-latest": {
		ID:          "gemini-flash-lite-latest",
		Name:        "Gemini Flash-Lite Latest",
		Family:      "gemini-flash-lite",
		Knowledge:   "2025-01",
		ReleaseDate: "2025-09-25",
		LastUpdated: "2025-09-25",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "toggle",
				},
				{
					Type: "budget_tokens",
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      0.1,
			Output:     0.4,
			CacheRead:  0.025,
			CacheWrite: 0,
		},
	},
	"gemini-omni-flash-preview": {
		ID:          "gemini-omni-flash-preview",
		Name:        "Gemini Omni Flash Preview",
		Family:      "gemini",
		ReleaseDate: "2026-06-30",
		LastUpdated: "2026-06-30",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 131072,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
			},
			Outputs: []llm.Modality{
				llm.ModalityVideo,
			},
		},
		OpenWeights: false,
		Pricing: llm.Pricing{
			Input:      1.5,
			Output:     17.5,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemma-4-26b-a4b-it": {
		ID:          "gemma-4-26b-a4b-it",
		Name:        "Gemma 4 26B A4B IT",
		Family:      "gemma",
		ReleaseDate: "2026-04-02",
		LastUpdated: "2026-04-02",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "toggle",
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 262144,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
		Pricing: llm.Pricing{
			Input:      0,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
	"gemma-4-31b-it": {
		ID:          "gemma-4-31b-it",
		Name:        "Gemma 4 31B IT",
		Family:      "gemma",
		ReleaseDate: "2026-04-02",
		LastUpdated: "2026-04-02",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
			ReasoningOptions: []llm.ReasoningOption{
				{
					Type: "toggle",
				},
			},
		},
		Limits: llm.ProfileLimits{
			Context: 262144,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
		Pricing: llm.Pricing{
			Input:      0,
			Output:     0,
			CacheRead:  0,
			CacheWrite: 0,
		},
	},
}
