// Code generated by loomgen; DO NOT EDIT.
// This file was generated by running the command:
//   loom-gen llm-profiles -provider=google -out=profiles.gen.go -pkg=loomgenai

package loomgenai

import "github.com/masterkeysrd/loom/llm"

var staticProfiles = map[string]llm.ModelProfile{
	"gemini-1.5-flash": {
		ID:     "gemini-1.5-flash",
		Name:   "Gemini 1.5 Flash",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-1.5-flash-8b": {
		ID:     "gemini-1.5-flash-8b",
		Name:   "Gemini 1.5 Flash-8B",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-1.5-pro": {
		ID:     "gemini-1.5-pro",
		Name:   "Gemini 1.5 Pro",
		Family: "gemini-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.0-flash": {
		ID:     "gemini-2.0-flash",
		Name:   "Gemini 2.0 Flash",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.0-flash-lite": {
		ID:     "gemini-2.0-flash-lite",
		Name:   "Gemini 2.0 Flash Lite",
		Family: "gemini-flash-lite",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash": {
		ID:     "gemini-2.5-flash",
		Name:   "Gemini 2.5 Flash",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-image": {
		ID:     "gemini-2.5-flash-image",
		Name:   "Gemini 2.5 Flash Image",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 32768,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-image-preview": {
		ID:     "gemini-2.5-flash-image-preview",
		Name:   "Gemini 2.5 Flash Image (Preview)",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 32768,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-lite": {
		ID:     "gemini-2.5-flash-lite",
		Name:   "Gemini 2.5 Flash Lite",
		Family: "gemini-flash-lite",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-lite-preview-06-17": {
		ID:     "gemini-2.5-flash-lite-preview-06-17",
		Name:   "Gemini 2.5 Flash Lite Preview 06-17",
		Family: "gemini-flash-lite",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-lite-preview-09-2025": {
		ID:     "gemini-2.5-flash-lite-preview-09-2025",
		Name:   "Gemini 2.5 Flash Lite Preview 09-25",
		Family: "gemini-flash-lite",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-preview-04-17": {
		ID:     "gemini-2.5-flash-preview-04-17",
		Name:   "Gemini 2.5 Flash Preview 04-17",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-preview-05-20": {
		ID:     "gemini-2.5-flash-preview-05-20",
		Name:   "Gemini 2.5 Flash Preview 05-20",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-preview-09-2025": {
		ID:     "gemini-2.5-flash-preview-09-2025",
		Name:   "Gemini 2.5 Flash Preview 09-25",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-flash-preview-tts": {
		ID:     "gemini-2.5-flash-preview-tts",
		Name:   "Gemini 2.5 Flash Preview TTS",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 8000,
			Output:  16000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityAudio,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-pro": {
		ID:     "gemini-2.5-pro",
		Name:   "Gemini 2.5 Pro",
		Family: "gemini-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-pro-preview-05-06": {
		ID:     "gemini-2.5-pro-preview-05-06",
		Name:   "Gemini 2.5 Pro Preview 05-06",
		Family: "gemini-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-pro-preview-06-05": {
		ID:     "gemini-2.5-pro-preview-06-05",
		Name:   "Gemini 2.5 Pro Preview 06-05",
		Family: "gemini-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-2.5-pro-preview-tts": {
		ID:     "gemini-2.5-pro-preview-tts",
		Name:   "Gemini 2.5 Pro Preview TTS",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 8000,
			Output:  16000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityAudio,
			},
		},
		OpenWeights: false,
	},
	"gemini-3-flash-preview": {
		ID:     "gemini-3-flash-preview",
		Name:   "Gemini 3 Flash Preview",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-3-pro-preview": {
		ID:     "gemini-3-pro-preview",
		Name:   "Gemini 3 Pro Preview",
		Family: "gemini-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1000000,
			Output:  64000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-3.1-flash-image-preview": {
		ID:     "gemini-3.1-flash-image-preview",
		Name:   "Gemini 3.1 Flash Image (Preview)",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 131072,
			Output:  32768,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
		},
		OpenWeights: false,
	},
	"gemini-3.1-flash-lite-preview": {
		ID:     "gemini-3.1-flash-lite-preview",
		Name:   "Gemini 3.1 Flash Lite Preview",
		Family: "gemini-flash-lite",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-3.1-pro-preview": {
		ID:     "gemini-3.1-pro-preview",
		Name:   "Gemini 3.1 Pro Preview",
		Family: "gemini-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-3.1-pro-preview-customtools": {
		ID:     "gemini-3.1-pro-preview-customtools",
		Name:   "Gemini 3.1 Pro Preview Custom Tools",
		Family: "gemini-pro",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityVideo,
				llm.ModalityAudio,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-embedding-001": {
		ID:     "gemini-embedding-001",
		Name:   "Gemini Embedding 001",
		Family: "gemini",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 2048,
			Output:  3072,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-flash-latest": {
		ID:     "gemini-flash-latest",
		Name:   "Gemini Flash Latest",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-flash-lite-latest": {
		ID:     "gemini-flash-lite-latest",
		Name:   "Gemini Flash-Lite Latest",
		Family: "gemini-flash-lite",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 1048576,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
				llm.ModalityPDF,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: false,
	},
	"gemini-live-2.5-flash": {
		ID:     "gemini-live-2.5-flash",
		Name:   "Gemini Live 2.5 Flash",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 128000,
			Output:  8000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
				llm.ModalityAudio,
				llm.ModalityVideo,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityAudio,
			},
		},
		OpenWeights: false,
	},
	"gemini-live-2.5-flash-preview-native-audio": {
		ID:     "gemini-live-2.5-flash-preview-native-audio",
		Name:   "Gemini Live 2.5 Flash Preview Native Audio",
		Family: "gemini-flash",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: false,
		},
		Limits: llm.ProfileLimits{
			Context: 131072,
			Output:  65536,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityAudio,
				llm.ModalityVideo,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityAudio,
			},
		},
		OpenWeights: false,
	},
	"gemma-3-12b-it": {
		ID:     "gemma-3-12b-it",
		Name:   "Gemma 3 12B",
		Family: "gemma",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 32768,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
	},
	"gemma-3-27b-it": {
		ID:     "gemma-3-27b-it",
		Name:   "Gemma 3 27B",
		Family: "gemma",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 131072,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
	},
	"gemma-3-4b-it": {
		ID:     "gemma-3-4b-it",
		Name:   "Gemma 3 4B",
		Family: "gemma",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 32768,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
	},
	"gemma-3n-e2b-it": {
		ID:     "gemma-3n-e2b-it",
		Name:   "Gemma 3n 2B",
		Family: "gemma",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 8192,
			Output:  2000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
	},
	"gemma-3n-e4b-it": {
		ID:     "gemma-3n-e4b-it",
		Name:   "Gemma 3n 4B",
		Family: "gemma",
		Capabilities: llm.Capabilities{
			Attachment:  true,
			Reasoning:   false,
			ToolCall:    false,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 8192,
			Output:  2000,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
	},
	"gemma-4-26b-a4b-it": {
		ID:     "gemma-4-26b-a4b-it",
		Name:   "Gemma 4 26B",
		Family: "gemma",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 256000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
	},
	"gemma-4-31b-it": {
		ID:     "gemma-4-31b-it",
		Name:   "Gemma 4 31B",
		Family: "gemma",
		Capabilities: llm.Capabilities{
			Attachment:  false,
			Reasoning:   true,
			ToolCall:    true,
			Temperature: true,
		},
		Limits: llm.ProfileLimits{
			Context: 256000,
			Output:  8192,
		},
		Modalities: llm.Modalities{
			Inputs: []llm.Modality{
				llm.ModalityText,
				llm.ModalityImage,
			},
			Outputs: []llm.Modality{
				llm.ModalityText,
			},
		},
		OpenWeights: true,
	},
}
